---
- name : Control OCI NSG
  connection: local
  hosts: localhost
  gather_facts: no
  serial: 1
  vars_files:
    - ../vars/nsg_add_rule_list.yml
  tasks:
    - name: List network_security_group_security_rules
      oracle.oci.oci_network_security_group_security_rule_facts:
        network_security_group_id: '{{ network_security_group_id }}'
      register: result
    - name: Dump result
      debug: 
        msg: '{{result}}'
